### ISSUE TITLE
Docs improperly shows how to parse DisplayBPM Range

### ISSUE THREAD

**Issue by zaneneuschuler** [garcia/simfile#48]
[In the docs for timing and note data](https://simfile.readthedocs.io/en/latest/timing-note-data.html#getting-the-displayed-bpm) for parsing DisplayBPMs, it incorrectly shows how to parse a DisplayBPM Range:

```py
elif disp.range:
    print(f"Range of values: {disp.value[0]}-{disp.value[1]}")
```

This will just cause an error, what should be in the docs instead is 

```py
elif disp.range:
    print(f"Range of values: {disp.range[0]}-{disp.range[1]}")
```

**Comment by garcia** [comment]
Fixed in https://github.com/garcia/simfile/commit/0bb52553a9c7f50ca6b8311e02431d9db0ac14f4. Thanks for the report!
